# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dcbef5f8f1278fd181a7480e25e1d9d6b5847adc955ad8dda84b351d8b744a6ca78914fe75414fc6804f43bca80087606eab93e662b6e9b3d7555c7e81dfb37f

test:
  secret_key_base: 7cf5d7e6139e202d96b8c436f9bd4bcd6fc743c19e9c4957b300fd295c8a33d1e4d206788d622c6a23d5dc1448ca661eb00e7ce584a1bda2f759709c48b6dba0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
